### ISSUE TITLE
Project is archived: add banner and update CNCF-project status

### ISSUE THREAD

**Issue by chalin** [brigadecore/brigade-www#90]
Contributes to:

- https://github.com/brigadecore/brigade/issues/1983

Tasks:

- [x] Update project's CNCF-status on the homepage to be **archived** - #91
- [x] Add a banner announcing that the project is now in archived status - #91
- [ ] Add a "banner" to the README - #92

/assign @chalin
